# Generated by Django 6.0.5 on 2026-06-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('rent', 'Rent/Utilities'), ('entertainment', 'Entertainment'), ('transport', 'Transportation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('business', 'Business'), ('gift', 'Gift'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
    ]
